GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: Token a7dac5cc54a6d2fbce3548a38d37c9ed8523fedc
###

POST https://api.nexus-banking.com/auth/token/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"anas@gmail.com",
    "password":"test"
}

###
POST http://127.0.0.1:8000/auth/token/logout/ HTTP/1.1
Authorization: Token 177d769f69dc726f88e783f6d15bbc49084af3ff
###
POST https://api.nexus-banking.com/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email":"anas@gmail.com",
    "password":"test"
}
###
GET https://api.nexus-banking.com/auth/users/me/ HTTP/1.1
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyODkxNTQxLCJpYXQiOjE3NjI4OTEyNDEsImp0aSI6IjRmZjQwODExYzhlOTQ1NDU5MjI3YTM4ZDllMWEyZWE3IiwidXNlcl9pZCI6IjIifQ.zNioGKdN6QJnYPZpXY-3rstXpwE9UrKVgOD3zLU0uyU

###
POST http://127.0.0.1:8000/auth/jwt/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc2MjYwNzQ0NCwiaWF0IjoxNzYyNTIxMDQ0LCJqdGkiOiJmYzM5N2RlMjNmYWQ0N2U4ODUzNzUzZTk3ZGIwZTQ3OCIsInVzZXJfaWQiOiIxIn0.MKK5QcnvzTj7fV4QZhnhfRE55jhQ7N0GPtqSA9_dgYs"
}

###
POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email":"salamehokoor@gmail.com",
    "password":"test@test"
}

###

POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email":"salameh@test.com",
    "password":"test@test"
}
###
curl -X POST http://127.0.0.1:8000/auth/jwt/create/ \
  -H "Content-Type: application/json" \
  -H "X-Forwarded-For: 92.253.28.65" \
  -d '{"email":"salamehokoor@gmail.com","password":"test@test"}'
###
curl -X POST 'https://api.nexus-banking.com/auth/jwt/create/' \
  -H "Content-Type: application/json" \
  -H "X-Forwarded-For: 154.45.12.88" \
  -d '{"email":"salamehokoor@gmail.com","password":"test@test"}'
###

