GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization: Token a7dac5cc54a6d2fbce3548a38d37c9ed8523fedc
###

POST http://127.0.0.1:8000/auth/token/login/ HTTP/1.1
Content-Type: application/json

{
    "email":"salamehokoor@gmail.com",
    "password":"test"
}

###
POST http://127.0.0.1:8000/auth/token/logout/ HTTP/1.1
Authorization: Token a7dac5cc54a6d2fbce3548a38d37c9ed8523fedc
###
POST http://127.0.0.1:8000/auth/jwt/create/ HTTP/1.1
Content-Type: application/json

{
    "email":"salamehokoor@gmail.com",
    "password":"test"
}
###
GET http://127.0.0.1:8000/auth/users/me/ HTTP/1.1
Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYyNTIxMjE4LCJpYXQiOjE3NjI1MjA5MTgsImp0aSI6ImM5ZDYyYjE2N2IwNTQxNjhhMzhmYzY3YmQ4MzliMTdmIiwidXNlcl9pZCI6IjEifQ.3GdKLkuqLFL2EYDkig248L2uuawFTqJLA4lvGudBpWU