# Generated by Django 5.2.8 on 2025-11-06 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='api_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], default='DEBIT', max_length=10)),
                ('card_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('cvv', models.CharField(editable=False, max_length=3)),
                ('expiration_date', models.DateField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
