# Generated by Django 5.2.8 on 2025-11-08 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='231', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 9, 1, 34, 36, 501968), editable=False),
        ),
    ]
