# Generated by Django 5.2.7 on 2025-11-07 11:05

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_groups_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=api.models.Account.generate_account_number, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
