# Generated by Django 5.2.8 on 2025-11-11 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(
                2030, 11, 11, 19, 11, 53, 288810),
                                   editable=False),
        ),
    ]
