# Generated by Django 5.2.8 on 2025-11-11 19:07

import datetime
from django.db import migrations, models


def set_currency_jod(apps, schema_editor):
    Account = apps.get_model('api', 'Account')
    Account.objects.filter(currency__isnull=True).update(currency='JOD')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('JOD', 'JOD'), ('USD', 'USD'),
                                            ('EUR', 'EUR')],
                                   default='JOD',
                                   max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[
                ('Savings', 'Savings Account'),
                ('Salary', 'Salary Account'),
                ('Basic', 'Basic Account'),
                ('USD', 'USD Account'),
                ('EUR', 'EUR Account'),
            ],
                                   default='Basic',
                                   max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='185', editable=False,
                                   max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(
                2030, 11, 11, 22, 7, 26, 560659),
                                   editable=False),
        ),
        migrations.RunPython(set_currency_jod, migrations.RunPython.noop),
    ]
