# Generated by Django 5.2.8 on 2025-11-11 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='749', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 11, 18, 16, 25, 11966), editable=False),
        ),
    ]
