# Generated by Django 5.2.7 on 2025-11-07 11:15

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_account_number_alter_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_type',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=api.models.Card.generate_card_number, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='184', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 7, 14, 15, 49, 181316), editable=False),
        ),
    ]
