# Generated by Django 5.2.8 on 2025-11-11 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_currency_alter_account_type_alter_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='200', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 11, 22, 10, 14, 689103), editable=False),
        ),
    ]
