# Generated by Django 5.2.7 on 2025-11-07 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_card_card_type_alter_card_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card')], default='DEBIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='217', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 7, 14, 18, 26, 430397), editable=False),
        ),
    ]
