# Generated by Django 5.2.7 on 2025-11-07 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_card_cvv_alter_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='373', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 7, 14, 29, 34, 31004), editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_balance_after',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_balance_after',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
    ]
