# Generated by Django 5.2.7 on 2025-11-07 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_card_cvv_alter_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='127', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 7, 14, 34, 24, 300467), editable=False),
        ),
    ]
