# Generated by Django 5.2.8 on 2025-11-17 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='257', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 18, 0, 52, 18, 210362), editable=False),
        ),
    ]
