# Generated by Django 5.2.8 on 2025-11-19 15:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='312', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 19, 18, 29, 43, 638310), editable=False),
        ),
    ]
