# Generated by Django 5.2.8 on 2025-11-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_billpayment_created_at_alter_card_cvv_and_more'),
        ('api', '0022_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
    ]
