# Generated by Django 5.2.8 on 2025-11-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_merge_20251120_2127'),
        ('api', '0025_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
    ]
