# Generated by Django 5.2.8 on 2025-11-24 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='275', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2030, 11, 24, 23, 42, 47, 221810), editable=False),
        ),
    ]
