# Generated by Django 5.2.8 on 2025-12-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20251122_1829'),
        ('api', '0031_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
    ]
