# Generated by Django 5.2.8 on 2025-12-04 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_card_cvv_alter_card_expiration_date'),
        ('api', '0034_merge_20251204_1601'),
        ('api', '0035_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
    ]
