# Generated by Django 5.2.8 on 2025-12-05 14:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_card_cvv_alter_card_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(default=api.models.generate_account_number_default, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
