# Generated by Django 5.2.8 on 2025-12-15 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2,
                                      default=Decimal('0.00'),
                                      max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='idempotency_key',
            field=models.CharField(blank=True,
                                   max_length=64,
                                   null=True,
                                   unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'),
                                            ('FAILED', 'Failed'),
                                            ('REVERSED', 'Reversed')],
                                   default='SUCCESS',
                                   max_length=16),
        ),
    ]
