# Generated by Django 5.2.8 on 2025-12-15 00:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_transaction_status_fee_idempotency_and_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True,
                                       default=django.utils.timezone.now),
        ),
    ]
