# Generated by Django 5.2.8 on 2025-12-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_biller_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='biller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
