# Generated by Django 5.2.8 on 2026-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='gemini_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
