# Generated by Django 5.2.8 on 2025-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='attempted_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='attempted_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
