# Generated by Django 5.2.8 on 2025-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_incident_attempted_email_loginevent_attempted_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='source',
            field=models.CharField(choices=[('password', 'Password (Djoser/JWT/Admin)'), ('google', 'Google OAuth'), ('other', 'Other')], default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='attempted_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
