# Generated by Django 5.2.8 on 2025-12-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_loginevent_failure_reason_loginevent_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
