# Generated by Django 5.2.8 on 2025-12-04 16:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('window', models.CharField(choices=[('dau', 'DAU'), ('wau', 'WAU'), ('mau', 'MAU')], max_length=8)),
                ('active_users', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='business_ac_date_82c843_idx'), models.Index(fields=['window'], name='business_ac_window_51ed69_idx'), models.Index(fields=['date', 'window'], name='business_ac_date_86953d_idx')],
                'unique_together': {('date', 'window')},
            },
        ),
        migrations.CreateModel(
            name='CountryUserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('tx_count', models.IntegerField(default=0)),
                ('tx_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'ordering': ['-date', 'country'],
                'indexes': [models.Index(fields=['date'], name='business_co_date_ebc96c_idx'), models.Index(fields=['country'], name='business_co_country_71982a_idx'), models.Index(fields=['date', 'country'], name='business_co_date_194f9a_idx')],
                'unique_together': {('date', 'country')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=16)),
                ('tx_count', models.IntegerField(default=0)),
                ('tx_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fx_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fee_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fx_spread_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'ordering': ['-date', 'currency'],
                'indexes': [models.Index(fields=['date'], name='business_cu_date_ecfe49_idx'), models.Index(fields=['currency'], name='business_cu_currenc_6ed32a_idx'), models.Index(fields=['date', 'currency'], name='business_cu_date_3193cf_idx')],
                'unique_together': {('date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='DailyBusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('active_users_7d', models.IntegerField(default=0)),
                ('active_users_30d', models.IntegerField(default=0)),
                ('total_transactions_success', models.IntegerField(default=0)),
                ('total_transactions_failed', models.IntegerField(default=0)),
                ('total_transactions_refunded', models.IntegerField(default=0)),
                ('total_transferred_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_chargeback_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('avg_transaction_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fx_volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bill_payments_count', models.IntegerField(default=0)),
                ('bill_payments_failed', models.IntegerField(default=0)),
                ('bill_payments_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fee_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bill_commission_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fx_spread_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('failed_logins', models.IntegerField(default=0)),
                ('incidents', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='business_da_date_2698c1_idx'), models.Index(fields=['-date'], name='business_da_date_d75bef_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_transactions_success', models.IntegerField(default=0)),
                ('total_transactions_failed', models.IntegerField(default=0)),
                ('total_transactions_refunded', models.IntegerField(default=0)),
                ('total_transferred_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bill_payments_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fee_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bill_commission_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fx_spread_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='business_mo_month_439822_idx'), models.Index(fields=['-month'], name='business_mo_month_b245c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField()),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_transactions_success', models.IntegerField(default=0)),
                ('total_transactions_failed', models.IntegerField(default=0)),
                ('total_transactions_refunded', models.IntegerField(default=0)),
                ('total_transferred_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bill_payments_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fee_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('bill_commission_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('fx_spread_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
            ],
            options={
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['week_start'], name='business_we_week_st_c8aaad_idx'), models.Index(fields=['-week_start'], name='business_we_week_st_241ecc_idx')],
            },
        ),
    ]
