# Generated by Django 5.2.8 on 2025-11-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBusinessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bill_payments_count', models.IntegerField(default=0)),
                ('bill_payments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('failed_logins', models.IntegerField(default=0)),
                ('incidents', models.IntegerField(default=0)),
                ('fx_volume', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bill_payments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryUserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'country')},
            },
        ),
    ]
