# Generated by Django 5.2.8 on 2025-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('week_end', models.DateField()),
                ('new_users', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_transferred_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bill_payments_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
