# Generated by Django 5.2.8 on 2025-12-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_overhaul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryusermetrics',
            options={'ordering': ['-date', 'country']},
        ),
        migrations.AlterModelOptions(
            name='monthlysummary',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='weeklysummary',
            options={'ordering': ['-week_start']},
        ),
        migrations.RenameIndex(
            model_name='countryusermetrics',
            new_name='business_co_date_ebc96c_idx',
            old_name='business_co_date_5e1c0b_idx',
        ),
        migrations.RenameIndex(
            model_name='countryusermetrics',
            new_name='business_co_country_71982a_idx',
            old_name='business_co_country_3b8698_idx',
        ),
        migrations.RenameIndex(
            model_name='countryusermetrics',
            new_name='business_co_date_194f9a_idx',
            old_name='business_co_date_co_0b68a4_idx',
        ),
        migrations.RenameIndex(
            model_name='currencymetrics',
            new_name='business_cu_date_ecfe49_idx',
            old_name='business_cu_date_9017d0_idx',
        ),
        migrations.RenameIndex(
            model_name='currencymetrics',
            new_name='business_cu_currenc_6ed32a_idx',
            old_name='business_cu_currency_a438c8_idx',
        ),
        migrations.RenameIndex(
            model_name='currencymetrics',
            new_name='business_cu_date_3193cf_idx',
            old_name='business_cu_date_cu_1af496_idx',
        ),
        migrations.RenameIndex(
            model_name='dailybusinessmetrics',
            new_name='business_da_date_2698c1_idx',
            old_name='business_da_date_0a6f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='dailybusinessmetrics',
            new_name='business_da_date_d75bef_idx',
            old_name='business_da__date_63fa8b_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlysummary',
            new_name='business_mo_month_439822_idx',
            old_name='business_mo_month_344f3b_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlysummary',
            new_name='business_mo_month_b245c9_idx',
            old_name='business_mo__month_23287e_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklysummary',
            new_name='business_we_week_st_c8aaad_idx',
            old_name='business_we_week_st_39e4c0_idx',
        ),
        migrations.RenameIndex(
            model_name='weeklysummary',
            new_name='business_we_week_st_241ecc_idx',
            old_name='business_we__week_s_8c4979_idx',
        ),
        migrations.AddIndex(
            model_name='activeuserwindow',
            index=models.Index(fields=['date'], name='business_ac_date_82c843_idx'),
        ),
        migrations.AddIndex(
            model_name='activeuserwindow',
            index=models.Index(fields=['window'], name='business_ac_window_51ed69_idx'),
        ),
        migrations.AddIndex(
            model_name='activeuserwindow',
            index=models.Index(fields=['date', 'window'], name='business_ac_date_86953d_idx'),
        ),
    ]
