# Generated by Django 5.2.8 on 2025-12-15 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActiveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('date', models.DateField()),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='dailyactiveuser',
            index=models.Index(fields=['date'], name='business_d_date_b000a0_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactiveuser',
            index=models.Index(fields=['user'], name='business_d_user_id_0341f2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactiveuser',
            index=models.Index(fields=['date', 'user'],
                               name='business_d_date_us_a74cb7_idx'),
        ),
    ]
