# Generated by Django 5.2.8 on 2025-12-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_dailyactiveuser'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailyactiveuser',
            new_name='business_da_date_a4bc82_idx',
            old_name='business_d_date_b000a0_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyactiveuser',
            new_name='business_da_user_id_681b2e_idx',
            old_name='business_d_user_id_0341f2_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyactiveuser',
            new_name='business_da_date_7d6a7f_idx',
            old_name='business_d_date_us_a74cb7_idx',
        ),
    ]
