# Generated by Django 5.2.8 on 2026-01-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_business_d_date_b000a0_idx_business_da_date_a4bc82_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('report_text', models.TextField(help_text='Deterministic business report text (human-readable)')),
                ('report_json', models.JSONField(default=dict, help_text='Structured metrics summary for AI context')),
                ('ai_output', models.TextField(blank=True, help_text='AI-generated analysis (null if API unavailable)', null=True)),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='AI model used for analysis', max_length=64)),
            ],
            options={
                'verbose_name': 'Daily AI Insight',
                'verbose_name_plural': 'Daily AI Insights',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='business_da_date_1b7cb5_idx'), models.Index(fields=['-date'], name='business_da_date_4780f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month', unique=True)),
                ('report_text', models.TextField(help_text='Deterministic business report text (human-readable)')),
                ('report_json', models.JSONField(default=dict, help_text='Structured metrics summary for AI context')),
                ('ai_output', models.TextField(blank=True, help_text='AI-generated analysis (null if API unavailable)', null=True)),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='AI model used for analysis', max_length=64)),
            ],
            options={
                'verbose_name': 'Monthly AI Insight',
                'verbose_name_plural': 'Monthly AI Insights',
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['month'], name='business_mo_month_5c6dfb_idx'), models.Index(fields=['-month'], name='business_mo_month_155370_idx')],
            },
        ),
    ]
