# Generated by Django 5.2.8 on 2026-01-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_ai_insight_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybusinessmetrics',
            name='metrics_by_currency',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown by currency: {'JOD': {'amount': 5000}, 'USD': {'amount': 2000}}"),
        ),
        migrations.AddField(
            model_name='dailybusinessmetrics',
            name='metrics_by_region',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown by region: {'Jordan': {'users': 50, 'tx_count': 100}, ...}"),
        ),
        migrations.AddField(
            model_name='dailybusinessmetrics',
            name='metrics_by_type',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown by activity type: {'transfer': 100, 'bill_payment': 20}"),
        ),
    ]
