# Generated by Django 5.2.8 on 2026-01-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_add_granular_bi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybusinessmetrics',
            name='ai_insight',
            field=models.TextField(blank=True, help_text="AI-generated insight comparing this day's performance to the previous day", null=True),
        ),
    ]
